config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'

  get 'contacts/create'

  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => 'login'
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => 'logout'
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/new'
  end

  namespace :admin do
    get 'users/create'
  end

  namespace :admin do
    get 'users/edit'
  end

  namespace :admin do
    get 'users/update'
  end

  namespace :admin do
    get 'users/destroy'
  end

  namespace :admin do
    get 'users/index'
  end

  namespace :admin do
    get 'users/show'
  end

  namespace :admin do
    get 'comments/destroy'
  end

  get 'comments/new'

  namespace :admin do
    get 'categories/new'
  end

  namespace :admin do
    get 'categories/create'
  end

  namespace :admin do
    get 'categories/edit'
  end

  namespace :admin do
    get 'categories/update'
  end

  namespace :admin do
    get 'categories/destroy'
  end

  namespace :admin do
    get 'categories/index'
  end

  namespace :admin do
    get 'categories/show'
  end

  get 'categories/show'

  namespace :admin do
    get 'posts/new'
  end

  namespace :admin do
    get 'posts/create'
  end

  namespace :admin do
    get 'posts/edit'
  end

  namespace :admin do
    get 'posts/update'
  end

  namespace :admin do
    get 'posts/destroy'
  end

  namespace :admin do
    get 'posts/index'
  end

  namespace :admin do
    get 'posts/show'
  end

  get 'posts/show'

  resources :posts, :categories

  resources 'contacts', only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  validates :name, presence: true

  def self.search(query)
    where('name like ?', "%#{query}%")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :verify_logged_in

  def new
    @page_title = 'Agregar categoría'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Categoría agregada'
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Categoría actualizada'
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = 'Categoría removida'
      redirect_to admin_categories_path
    else
      flash[:alert] = 'La categoría no pudo ser removida, intente de nuevo'
      redirect_to admin_categories_path
    end
  end

  def index
    if params[:search]
      @categories = Category.search(params[:search]).all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    else
      @categories = Category.all.order('created_at DESC').paginate(per_page: 10, page: params[:page])
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @categories = Category.all.order('created_at DESC')
    @posts = @category.posts.order('created_at DESC').paginate(per_page: 10, page: params[:page])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h2>editar categoría</h2>
<%= form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_message.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <%= f.submit 'Guardar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', admin_categories_path, class:'btn btn-default' %>
<% end %>

app/views/admin/categories/index.html.erb
<h2 class="page-header">Administración de categorias <%= link_to 'Agregar nueva',
new_admin_category_path, class:'btn btn-success pull-right' %></h2>
<table class="table table-striped">
  <tr>
    <th>Nombre</th>
    <th>Fecha de creación</th>
    <th>Acciones</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.created_at.to_time.strftime('%e %B a las %l:%M %p') %></td>
      <td><%= link_to 'Editar', edit_admin_category_path(category), class:'btn btn-primary' %>
      <%= link_to 'Eliminar', admin_category_path(category), method: :delete, data: { confirm: 'Estas seguro?' },
      class:'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @posts %>

app/views/admin/categories/new.html.erb
<h2>Agregar nueva categoría</h2>
<%= form_for [:admin, @category] do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, 'Nombre' %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <br>
  <%= f.submit 'Agregar', class:'btn btn-primary' %>
  <%= link_to 'Cancelar', admin_categories_path, class:'btn btn-default' %>
<% end %>